package eu.mikart.tava.dialect;

public final class H2Dialect extends BaseDialect {
	public H2Dialect(String url) {
		this(url, "sa", "");
	}

	public H2Dialect(String url, String user, String password) {
		super(url, user, password);
	}

	@Override public String name() { return "h2"; }
	@Override public String typeUuid() { return "UUID"; }
	@Override public String typeString(int length) { return length > 0 ? "VARCHAR(" + length + ")" : "TEXT"; }
	@Override public String typeText() { return "TEXT"; }
	@Override public String typeInt() { return "INTEGER"; }
	@Override public String typeBigInt() { return "BIGINT"; }
	@Override public String typeBoolean() { return "BOOLEAN"; }
	@Override public String typeTimestamp() { return "TIMESTAMP WITH TIME ZONE"; }
	@Override public String typeJson() { return "JSON"; }
	@Override public String typeBinary() { return "BINARY LARGE OBJECT"; }
	@Override public String autoIncrement() { return "GENERATED BY DEFAULT AS IDENTITY"; }
	@Override public boolean supportsIfNotExists() { return true; }
	@Override public boolean supportsReturning() { return false; }
}
