package eu.mikart.tava.dialect;

public final class PostgresDialect extends BaseDialect {
	public PostgresDialect(String host, int port, String database, String user, String password) {
		super("jdbc:postgresql://" + host + ":" + port + '/' + database, user, password);
	}

	@Override
	public String name() {
		return "postgres";
	}

	@Override
	public String typeUuid() {
		return "UUID";
	}

	@Override
	public String typeString(int length) {
		return length > 0 ? "VARCHAR(" + length + ")" : "TEXT";
	}

	@Override
	public String typeText() {
		return "TEXT";
	}

	@Override
	public String typeInt() {
		return "INT";
	}

	@Override
	public String typeBigInt() {
		return "BIGINT";
	}

	@Override
	public String typeBoolean() {
		return "BOOLEAN";
	}

	@Override
	public String typeTimestamp() {
		return "TIMESTAMP";
	}

	@Override
	public String typeJson() {
		return "JSONB";
	}

	@Override
	public String autoIncrement() {
		return "GENERATED BY DEFAULT AS IDENTITY";
	}

	@Override
	public boolean supportsIfNotExists() {
		return true;
	}

	@Override
	public boolean supportsReturning() {
		return true;
	}
}
