package eu.mikart.tava.postgres;

import eu.mikart.tava.jdbc.JdbcAdapter;
import eu.mikart.tava.jdbc.StandardJdbcProfile;
import eu.mikart.tava.schema.FieldDefinition;
import org.jetbrains.annotations.NotNull;

public final class Postgres {
    private Postgres() {
    }

    public static @NotNull JdbcAdapter connect(
            final @NotNull String url,
            final @NotNull String user,
            final @NotNull String password
    ) {
        return JdbcAdapter.driverManager(new Profile(), url, user, password);
    }

    public static @NotNull JdbcAdapter connect(
            final @NotNull String host,
            final int port,
            final @NotNull String database,
            final @NotNull String user,
            final @NotNull String password
    ) {
        return connect("jdbc:postgresql://" + host + ":" + port + "/" + database, user, password);
    }

    private static final class Profile extends StandardJdbcProfile {
        private Profile() {
            super("postgres", '"', true);
        }

        @Override
        public @NotNull String type(final @NotNull FieldDefinition field) {
            return switch (field.type().logicalType()) {
                case UUID -> "UUID";
                case JSON -> "JSONB";
                case BINARY -> "BYTEA";
                case INSTANT -> "TIMESTAMP WITH TIME ZONE";
                default -> super.type(field);
            };
        }

        @Override
        public @NotNull String identityClause(final @NotNull FieldDefinition field) {
            return field.generated() == eu.mikart.tava.schema.GeneratedValue.IDENTITY
                    ? "GENERATED BY DEFAULT AS IDENTITY" : "";
        }
    }
}
