package eu.mikart.tava.postgres;

import eu.mikart.tava.jdbc.JdbcAdapter;
import eu.mikart.tava.jdbc.StandardJdbcProfile;
import eu.mikart.tava.schema.FieldDefinition;

public final class Postgres {
    private Postgres() {
    }

    public static JdbcAdapter connect(String url, String user, String password) {
        return JdbcAdapter.driverManager(new Profile(), url, user, password);
    }

    public static JdbcAdapter connect(String host, int port, String database, String user, String password) {
        return connect("jdbc:postgresql://" + host + ":" + port + "/" + database, user, password);
    }

    private static final class Profile extends StandardJdbcProfile {
        private Profile() {
            super("postgres", '"', true);
        }

        @Override
        public String type(FieldDefinition field) {
            return switch (field.type().logicalType()) {
                case UUID -> "UUID";
                case JSON -> "JSONB";
                case BINARY -> "BYTEA";
                case INSTANT -> "TIMESTAMP WITH TIME ZONE";
                default -> super.type(field);
            };
        }

        @Override
        public String identityClause(FieldDefinition field) {
            return field.generated() == eu.mikart.tava.schema.GeneratedValue.IDENTITY
                    ? "GENERATED BY DEFAULT AS IDENTITY" : "";
        }
    }
}
