package eu.mikart.tava.oracle;

import eu.mikart.tava.jdbc.JdbcAdapter;
import eu.mikart.tava.jdbc.StandardJdbcProfile;
import eu.mikart.tava.schema.FieldDefinition;
import org.jetbrains.annotations.NotNull;

public final class Oracle {
    private Oracle() {
    }

    public static @NotNull JdbcAdapter connect(
            final @NotNull String url,
            final @NotNull String user,
            final @NotNull String password
    ) {
        return JdbcAdapter.driverManager(new Profile(), url, user, password);
    }

    private static final class Profile extends StandardJdbcProfile {
        private Profile() {
            super("oracle", '"', false);
        }

        @Override
        public @NotNull String type(final @NotNull FieldDefinition field) {
            return switch (field.type().logicalType()) {
                case UUID -> "VARCHAR2(36)";
                case JSON, TEXT -> "CLOB";
                case STRING -> "VARCHAR2(" + (field.type().length() == null ? 255 : field.type().length()) + ")";
                case INT32 -> "NUMBER(10)";
                case INT64 -> "NUMBER(19)";
                case BOOLEAN -> "NUMBER(1)";
                case BINARY -> "BLOB";
                case INSTANT -> "TIMESTAMP WITH TIME ZONE";
                default -> super.type(field);
            };
        }

        @Override
        public @NotNull String identityClause(final @NotNull FieldDefinition field) {
            return field.generated() == eu.mikart.tava.schema.GeneratedValue.IDENTITY
                    ? "GENERATED BY DEFAULT AS IDENTITY" : "";
        }

        @Override
        public @NotNull String pagination(final int limit, final int offset) {
            return " OFFSET " + offset + " ROWS FETCH NEXT " + limit + " ROWS ONLY";
        }

        @Override
        public @NotNull String defaultPaginationOrder() {
            return " ORDER BY 1";
        }
    }
}
