package eu.mikart.tava.h2;

import eu.mikart.tava.jdbc.JdbcAdapter;
import eu.mikart.tava.jdbc.StandardJdbcProfile;
import eu.mikart.tava.schema.FieldDefinition;
import org.jetbrains.annotations.NotNull;

public final class H2 {
    private H2() {
    }

    public static @NotNull JdbcAdapter memory(final @NotNull String name) {
        return JdbcAdapter.driverManager(new Profile(), "jdbc:h2:mem:" + name + ";DB_CLOSE_DELAY=-1", "sa", "");
    }

    public static @NotNull JdbcAdapter connect(
            final @NotNull String url,
            final @NotNull String user,
            final @NotNull String password
    ) {
        return JdbcAdapter.driverManager(new Profile(), url, user, password);
    }

    private static final class Profile extends StandardJdbcProfile {
        private Profile() {
            super("h2", '"', true);
        }

        @Override
        public @NotNull String type(final @NotNull FieldDefinition field) {
            return switch (field.type().logicalType()) {
                case UUID -> "UUID";
                case JSON -> "JSON";
                case BINARY -> "BINARY LARGE OBJECT";
                case INSTANT -> "TIMESTAMP WITH TIME ZONE";
                default -> super.type(field);
            };
        }

        @Override
        public @NotNull String identityClause(final @NotNull FieldDefinition field) {
            return field.generated() == eu.mikart.tava.schema.GeneratedValue.IDENTITY
                    ? "GENERATED BY DEFAULT AS IDENTITY" : "";
        }
    }
}
