package eu.mikart.tava.h2;

import eu.mikart.tava.jdbc.JdbcAdapter;
import eu.mikart.tava.jdbc.StandardJdbcProfile;
import eu.mikart.tava.schema.FieldDefinition;

public final class H2 {
    private H2() {
    }

    public static JdbcAdapter memory(String name) {
        return JdbcAdapter.driverManager(new Profile(), "jdbc:h2:mem:" + name + ";DB_CLOSE_DELAY=-1", "sa", "");
    }

    public static JdbcAdapter connect(String url, String user, String password) {
        return JdbcAdapter.driverManager(new Profile(), url, user, password);
    }

    private static final class Profile extends StandardJdbcProfile {
        private Profile() {
            super("h2", '"', true);
        }

        @Override
        public String type(FieldDefinition field) {
            return switch (field.type().logicalType()) {
                case UUID -> "UUID";
                case JSON -> "JSON";
                case BINARY -> "BINARY LARGE OBJECT";
                case INSTANT -> "TIMESTAMP WITH TIME ZONE";
                default -> super.type(field);
            };
        }

        @Override
        public String identityClause(FieldDefinition field) {
            return field.generated() == eu.mikart.tava.schema.GeneratedValue.IDENTITY
                    ? "GENERATED BY DEFAULT AS IDENTITY" : "";
        }
    }
}
