package eu.mikart.tava.capability;

public enum Feature {
    SCHEMA_ENFORCEMENT, UNIQUE_CONSTRAINTS, FOREIGN_KEYS, SECONDARY_INDEXES,
    TRANSACTIONS, CONDITIONAL_WRITES, SORTING, PAGINATION, PROJECTION,
    JOINS, AGGREGATION, TTL, FULL_TEXT, GENERATED_VALUES, JSON, BINARY,
    BULK_READ, BULK_WRITE
}
